# Generated by Django 5.0.4 on 2024-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
